version: '3.9'

services:
  db:
    image: "postgres"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=app
      - POSTGRES_USER=app
      - POSTGRES_DB=parking

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      # RabbitMq instance
      - "5672:5672"
      # Web interface
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=app
      - RABBITMQ_DEFAULT_PASS=app

  s3-ninja:
    image: scireum/s3-ninja
    container_name: s3
    ports:
      - "9111:9000"
    volumes:
      - ./configs/s3:/home/sirius/data

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  parking-manager:
    build:
      context: ../backend/ParkingManager
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: on-failure
    depends_on:
      - db
      - s3-ninja
      - rabbitmq

  car-plate-recognizer:
    build:
      context: ../backend/car-plate-recognizer
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_USERNAME=app
      - RABBITMQ_PASSWORD=app
      - RABBITMQ_QUEUE_NAME=rpc_queue
    restart: on-failure
    depends_on:
      - rabbitmq
